"""Export the frozen wire schema/types and evaluator-computed invented UI fixtures.

Run from repository root with uv; --check detects drift without writing files.
No database, API, published dataset, or real source interpretation is involved.
"""

import argparse
import json
import sys
from copy import deepcopy
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from app.evaluation import EvaluationReport, evaluate  # noqa: E402
from tests.evaluation_fixtures import ORACLE, quantity, ref, request  # noqa: E402


def typescript(node):
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    for union in ("anyOf", "oneOf"):
        if union in node:
            return " | ".join(typescript(v) for v in node[union])
    kind = node.get("type")
    if kind == "object":
        required = node.get("required", [])
        return "{\n" + "\n".join(
            f'  {json.dumps(k)}{"" if k in required else "?"}: {typescript(v)}'
            for k, v in node["properties"].items()
        ) + "\n}"
    if kind == "array":
        if "prefixItems" in node:
            return "[" + ", ".join(typescript(v) for v in node["prefixItems"]) + "]"
        return f'Array<{typescript(node["items"])}>'
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("number", "integer"):
        return "number"
    raise ValueError(f"Unsupported schema shape: {node}")


def fixtures():
    cases = {}
    for alias in ("synthetic-direct-pass", "synthetic-missing-fact", "synthetic-placement-failure"):
        p = request()
        p["evaluation_id"] = alias
        if alias == "synthetic-missing-fact":
            p["facts"] = []
        if alias == "synthetic-placement-failure":
            p["facts"][0]["quantity"] = quantity("11")
        cases[alias] = p
    for field in ("rules", "bindings"):
        p = request()
        p[field] = []
        cases[f"absent-{field}"] = p
    p = request()
    p["scope"]["coverage"] = "outside_coverage"
    cases["outside-coverage"] = p
    p = request()
    p["rules"][0]["content"]["approval"] = "unknown"
    cases["unknown-approval"] = p
    p = request()
    p["alternatives"].append(
        dict(pathway_id="synthetic", alternative_id="B", rules=[ref("absent-rule")])
    )
    cases["unresolved-alternative"] = p
    p = request()
    basis = dict(numerator="regulatory_floor_area", denominator="regulatory_lot_area")
    p["facts"][0]["quantity"] = quantity("0.45", "fraction", basis=basis)
    p["rules"][0]["content"]["semantics"]["threshold"] = quantity("45", "%", "0.45", basis)
    cases["ratio"] = p
    p = request()
    p["sources"][0]["source_url"] = "file:///private/source.html"
    p["rules"][0]["content"]["evidence"][0]["excerpt"] = '<img src=x onerror="alert(1)">'
    cases["inert-evidence"] = p
    # The repo: artifact identifies Git's LF text, independent of checkout CRLF.
    digest = sha256(ORACLE.read_text(encoding="utf-8").encode("utf-8")).hexdigest()
    for payload in cases.values():
        payload["sources"][0]["artifact"]["sha256"] = digest
    return {k: json.loads(evaluate(deepcopy(v)).model_dump_json()) for k, v in cases.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = EvaluationReport.model_json_schema(mode="serialization")
    types = "// Generated by frontend/tools/export_draft_evaluations.py. Do not edit.\n"
    for name, node in {**schema["$defs"], "EvaluationReport": schema}.items():
        types += f"export type {name} = {typescript(node)}\n\n"
    outputs = {
        "schema.json": json.dumps(schema, indent=2) + "\n",
        "types.ts": types.rstrip() + "\n",
        "reports.test.json": json.dumps(fixtures(), indent=2) + "\n",
    }
    directory = ROOT / "frontend/src/draft_evaluations"
    directory.mkdir(exist_ok=True)
    for name, content in outputs.items():
        path = directory / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated file drift: {path.relative_to(ROOT)}")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    action = "verified" if args.check else "exported"
    print(f"Draft report schema, types and ten evaluator fixtures {action}")


if __name__ == "__main__":
    main()
