// Generated by frontend/tools/export_draft_evaluations.py. Do not edit.
export type AcceptedRuleRevision = {
  "schema_version": "sr-04.v1-provisional"
  "identity": RevisionRef
  "candidate_id": string
  "content": RuleContent
  "review": Review
  "supersedes": Array<RevisionRef>
  "identity_decision": string
}

export type Alternative = {
  "pathway_id": string
  "alternative_id": string
  "rules": Array<RevisionRef>
}

export type AlternativeResult = {
  "pathway_id": string
  "alternative_id": string
  "outcome": "candidate" | "needs_investigation" | "no_match_under_evaluated_pathways"
  "approval": "as_of_right" | "conditional" | "discretionary" | "unknown"
  "conditions": Array<string>
  "checks": Array<CheckResult>
}

export type Applicability = {
  "jurisdiction": string
  "use": string
  "building_role": string
  "conditions": Array<string>
  "exceptions": Array<string>
  "status": "reviewed_scope" | "unresolved"
}

export type Artifact = {
  "uri": string
  "sha256": string
}

export type Binding = {
  "rule": RevisionRef
  "fact": RevisionRef
  "inputs": InputRefs
  "measurement_definition": string
  "definition_support": "reviewed_direct_measurement" | "unsupported"
  "applicability": "applicable" | "unresolved"
  "provenance": Provenance
}

export type CheckResult = {
  "check_id": string
  "rule": RevisionRef | null
  "status": "pass" | "supported_failure" | "missing_fact" | "extraction_failure" | "outside_coverage" | "unsupported_semantics" | "unresolved_reference" | "not_applicable"
  "explanation": string
  "evidence": Array<Evidence>
  "missing_facts": Array<string>
}

export type CheckTrace = {
  "rule": RevisionRef
  "binding": Binding | null
  "fact": MeasuredFact | null
  "diagnostics": Array<string>
  "result": CheckResult
}

export type CoordinateReference = {
  "identifier": string
  "axis_order": "x_y"
  "unit": "m" | "ft" | "degree"
  "definition": string
}

export type DesignRevision = {
  "schema_version": "sr-04.v1-provisional"
  "identity": RevisionRef
  "configuration": string
  "adaptability": "fixed"
  "intended_use": string
  "construction_method": string
  "measurements": Array<Measurement>
  "provenance": Provenance
}

export type EvaluationRequest = {
  "schema_version": "sr-10.v1"
  "evaluator_version": "bounded-scalar.v1"
  "evaluation_id": string
  "draft": RevisionRef
  "data_state": "draft_only"
  "sources": Array<SourceSnapshot>
  "design": DesignRevision
  "site": SiteRevision
  "placement": PlacementRevision
  "scope": EvaluationScope
  "alternatives": Array<Alternative>
  "rules": Array<AcceptedRuleRevision>
  "facts": Array<MeasuredFact>
  "bindings": Array<Binding>
}

export type EvaluationScope = {
  "jurisdiction": string
  "use": string
  "building_role": string
  "coverage": "within_coverage" | "outside_coverage" | "unresolved"
  "description": string
  "exclusions": Array<string>
  "provenance": Provenance
}

export type Evidence = {
  "snapshot_id": string
  "locator": string
  "page_index"?: number | null
  "printed_page"?: string | null
  "excerpt": string
  "context": string
}

export type Geometry = {
  "kind": "polygon" | "line"
  "coordinates": Array<[string, string]>
  "crs": CoordinateReference
}

export type GeometryFact = {
  "fact_id": string
  "role": "parcel" | "principal_building" | "lot_line" | "rear_yard" | "proposed_placement"
  "status": "known" | "missing" | "uncertain"
  "geometry": Geometry | null
  "lot_line_classification"?: "front" | "rear" | "interior_side" | "exterior_side" | "unknown" | null
  "reason"?: string | null
  "provenance": Provenance
}

export type InputRefs = {
  "design": RevisionRef
  "site": RevisionRef
  "placement": RevisionRef
}

export type MeasuredFact = {
  "identity": RevisionRef
  "inputs": InputRefs
  "definition": string
  "status": "known" | "missing" | "uncertain"
  "quantity": Quantity | null
  "reason"?: string | null
  "provenance": Provenance
}

export type Measurement = {
  "name": "manufacturer_interior_area" | "nominal_exterior_width" | "nominal_exterior_depth" | "ceiling_height" | "roof_height" | "occupancy_footprint" | "regulatory_floor_area" | "regulatory_height" | "lot_area" | "lot_width" | "lot_depth" | "storeys" | "dwelling_units"
  "domain": "physical" | "regulatory"
  "definition": string
  "status": "known" | "missing" | "uncertain"
  "quantity": Quantity | null
  "reason"?: string | null
  "provenance": Provenance
}

export type PlacementRevision = {
  "schema_version": "sr-04.v1-provisional"
  "identity": RevisionRef
  "site": RevisionRef
  "design": RevisionRef
  "footprint": GeometryFact
  "scope": "supplied_placement_only"
}

export type Provenance = {
  "method": "source" | "supplied" | "manual" | "derived"
  "evidence": Array<Evidence>
  "review": Review
  "uncertainty": Array<string>
}

export type Quantity = {
  "original_text": string
  "original_value": string
  "original_unit": "m" | "ft" | "m2" | "ft2" | "count" | "%" | "fraction" | "spaces/unit"
  "dimension": "length" | "area" | "count" | "ratio" | "rate"
  "value": string
  "unit": "m" | "m2" | "count" | "fraction" | "spaces/unit"
  "basis"?: RatioBasis | null
}

export type RatioBasis = {
  "numerator": string
  "denominator": string
}

export type Review = {
  "status": "unreviewed" | "accepted" | "rejected" | "needs_review"
  "reviewer"?: string | null
  "reviewed_at"?: string | null
  "scope": string
  "rationale": string
}

export type RevisionRef = {
  "logical_id": string
  "revision_id": string
}

export type RuleContent = {
  "pathway_id": string
  "alternative_id": string
  "text": string
  "evidence": Array<Evidence>
  "applicability": Applicability
  "approval": "as_of_right" | "conditional" | "discretionary" | "unknown"
  "semantics": ScalarBound | UnresolvedSemantics
  "runtime_support": "supported" | "unsupported" | "unresolved"
  "references": Array<RuleReference>
}

export type RuleReference = {
  "instrument": string
  "locator": string
  "relationship": "depends_on" | "exception" | "excludes" | "overrides" | "calculation"
  "status": "unresolved" | "resolved"
  "target": RevisionRef | null
}

export type ScalarBound = {
  "kind": "scalar_bound"
  "subject": string
  "measurement_definition": string
  "operator": "<" | "<=" | ">" | ">=" | "=="
  "threshold": Quantity
}

export type SiteRevision = {
  "schema_version": "sr-04.v1-provisional"
  "identity": RevisionRef
  "jurisdiction": string
  "measurements": Array<Measurement>
  "geometry_facts": Array<GeometryFact>
  "conditions": Array<string>
  "provenance": Provenance
}

export type SourceSnapshot = {
  "schema_version": "sr-04.v1-provisional"
  "source_id": string
  "snapshot_id": string
  "category": "bylaw" | "guidance" | "design" | "spatial" | "manual_record" | "test_fixture"
  "jurisdiction": string
  "instrument": string
  "source_url": string
  "artifact": Artifact
  "captured_at": string
  "printed_revision": string | null
  "effective_from": string | null
  "effective_to": string | null
  "effective_date_evidence": Array<Evidence>
  "original_crs": string | null
  "original_units": Array<string>
  "reuse_constraints": string
  "review": Review
}

export type UnresolvedSemantics = {
  "kind": "unresolved"
  "text": string
  "reason": string
}

export type EvaluationReport = {
  "schema_version": "sr-10.v1"
  "evaluator_version": "bounded-scalar.v1"
  "data_state": "draft_only"
  "scope": "supplied_placement_only"
  "request": EvaluationRequest
  "outcome": "candidate" | "needs_investigation" | "no_match_under_evaluated_pathways"
  "alternatives": Array<AlternativeResult>
  "traces": Array<CheckTrace>
  "scope_exclusions": Array<string>
}
