import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import { renderToStaticMarkup } from 'react-dom/server'
import catalogue from '../model_catalogue/catalogue.json'
import { parseResult, parseSites } from '../occupied_lots/contract'
import ScenarioHandoff, { providerEnquiry, scenarioRecord } from './ScenarioHandoff'

// The assessment fixture was generated by the geometry engine from retained VIC-087
// geometry with a supplied 4 × 6 m rectangle and a 1.5 m user assumption. This test
// checks handoff semantics and lossless identity, not the engine's distance arithmetic.
const packet = JSON.parse(readFileSync('../app/scouting_sites/data/sites.json', 'utf8'))
const site = parseSites(packet)[0]
const assessment = parseResult(JSON.parse(readFileSync('src/scenario_handoff/retained-assessment.fixture.json', 'utf8')))
const model = catalogue.models[0]

test('retained placement stays complete in JSON and readable in an unsent enquiry', () => {
  const props = { site, model, assessment }
  const scenario = scenarioRecord(props)
  assert.ok(scenario)
  assert.deepEqual(scenario.site, site)
  assert.deepEqual(scenario.model, model)
  assert.deepEqual(scenario.assessment, assessment)
  assert.equal(scenario.schema_version, 'shovelready.scenario-handoff.v1')
  const draft = providerEnquiry(props)
  assert.ok(draft)
  assert.match(draft, /UNSENT DRAFT/)
  assert.match(draft, /1\.5 m/)
  assert.match(draft, /falls short/)
  assert.match(draft, /captured roofline 1/)
  assert.match(draft, /controlled drawing/)
  assert.doesNotMatch(draft, /sha256|snapshot_id|new-87-parcel:87|\?f=pjson/)
  assert.match(JSON.stringify(scenario), /new-87-parcel:87/)
  const html = renderToStaticMarkup(<ScenarioHandoff {...props} />)
  assert.match(html, /Download scenario JSON/)
  assert.match(html, /Copyable unsent provider enquiry/)
})

test('missing or mismatched site measurement cannot produce either export', () => {
  assert.equal(scenarioRecord({ site, model, assessment: null }), null)
  assert.equal(providerEnquiry({ site, model, assessment: null }), null)
  const altered = { ...site, site: { ...site.site, parcel: { ...site.site.parcel, id: 'another-parcel' } } }
  assert.equal(scenarioRecord({ site: altered, model, assessment }), null)
  assert.equal(providerEnquiry({ site: altered, model, assessment }), null)
  const html = renderToStaticMarkup(<ScenarioHandoff site={site} model={model} assessment={null} />)
  assert.match(html, /Measure the current site/)
  assert.doesNotMatch(html, /Download scenario JSON/)
})
